#!/bin/bash
set -o errexit

chmodf() { find $2 -type f -exec chmod -v $1 {} \;
}
chmodd() { find $2 -type d -exec chmod -v $1 {} \;
}

echo -e "\n========================================================"
# If DataDirectory, identity keys or torrc is mounted here,
# ownership needs to be changed to the TOR_USER user
chown -Rv ${TOR_USER}:${TOR_USER} /var/lib/tor
# fix permissions
chmodd 700 /var/lib/tor
chmodf 600 /var/lib/tor

if [ ! -e /tor-config-done ]; then
    touch /tor-config-done   # only run this once
    if [ -n "${TOR_DEBUG}" ]; then
      if ! grep -q '^PublishServerDescriptor ' /etc/tor/torrc; then
        echo "Setting PublishServerDescriptor: 0"
        echo -e "\nPublishServerDescriptor 0" >> /etc/tor/torrc
      fi
    fi

    # Add Nickname from env variable or randomized, if none has been set
    if ! grep -q '^Nickname ' /etc/tor/torrc; then
        if [ ${TOR_NICKNAME} == "Tor4" ] || [ -z "${TOR_NICKNAME}" ]; then
            # if user did not change the default Nickname, genetrate a random pronounceable one
            RPW=$(pwgen -0A 8)
            TOR_NICKNAME="Tor4${RPW}"
            echo "Setting random Nickname: ${TOR_NICKNAME}"
        else
            echo "Setting chosen Nickname: ${TOR_NICKNAME}"
        fi
        echo -e "\nNickname ${TOR_NICKNAME}" >> /etc/tor/torrc
    fi

    # Add Contact_Email from env variable, if none has been set in torrc
    if ! grep -q '^ContactInfo ' /etc/tor/torrc; then
        # if CONTACT_EMAIL is not null
        if [ -n "${CONTACT_EMAIL}" ]; then
            echo "Setting Contact Email: ${CONTACT_EMAIL}"
            echo -e "\nContactInfo ${CONTACT_EMAIL}" >> /etc/tor/torrc
        fi
    fi

    # Port to advertise for incoming Tor connections.
    if ! grep -q '^ORPort ' /etc/tor/torrc; then
        echo -e "\\nORPort 9001" >> /etc/tor/torrc
    fi

    # Run Tor only as a server (no local applications)
    if ! grep -q '^SocksPort ' /etc/tor/torrc; then
        echo -e "\\nSocksPort 0" >> /etc/tor/torrc
    fi

    # Run as a relay only (not as an exit node)
    if ! grep -q '^ExitPolicy ' /etc/tor/torrc; then
        echo -e "\\nExitPolicy reject *:*" >> /etc/tor/torrc
    fi

    # Run Tor as a regular user (do not change this)
    if ! grep -q '^User ' /etc/tor/torrc; then
        echo -e "\\nUser ${TOR_USER}" >> /etc/tor/torrc
    fi

    if ! grep -q '^DataDirectory ' /etc/tor/torrc; then
        echo -e "\\nDataDirectory /var/lib/tor" >> /etc/tor/torrc
    fi

    # Set the hard limit of open file descriptors really high.
    # Tor will also potentially run out of ports.
    echo "Setting ulimit..."
    ulimit -SHn 65000

    #echo "Setting nameservers..."
    #echo "nameserver 8.8.8.8" >> /etc/resolv.conf
    #echo "nameserver 4.2.2.2" >> /etc/resolv.conf

    #echo "Tune using sysctl..."
    #sudo sysctl net.ipv4.tcp_rmem="4096 87380 16777216"
    #sudo sysctl net.ipv4.tcp_wmem="4096 65536 16777216"
    #sudo sysctl net.core.netdev_max_backlog=2500
    #sudo sysctl net.ipv4.tcp_no_metrics_save=1
    #sudo sysctl net.ipv4.tcp_moderate_rcvbuf=1
    #sudo sysctl net.core.rmem_max=1048575
    #sudo sysctl net.core.wmem_max=1048575
    #sudo sysctl net.ipv4.ip_local_port_range="1025 61000"
    #sudo sysctl net.ipv4.tcp_synack_retries=3
    #sudo sysctl net.ipv4.tcp_tw_recycle=1
    #sudo sysctl net.ipv4.tcp_max_syn_backlog=10240
    #sudo sysctl net.ipv4.tcp_fin_timeout=30
    #sudo sysctl net.ipv4.tcp_keepalive_time=1200
    #sudo sysctl net.netfilter.nf_conntrack_tcp_timeout_established=7200
    #sudo sysctl net.netfilter.nf_conntrack_checksum=0
    #sudo sysctl net.netfilter.nf_conntrack_max=131072
    #sudo sysctl net.netfilter.nf_conntrack_tcp_timeout_syn_sent=15
    #sudo sysctl net.ipv4.tcp_keepalive_time=60
    #sudo sysctl net.ipv4.tcp_keepalive_time=60
    #sudo sysctl net.ipv4.tcp_keepalive_intvl=10
    #sudo sysctl net.ipv4.tcp_keepalive_probes=3
    #sudo sysctl net.ipv4.ip_local_port_range="1025 65530"
    #sudo sysctl net.core.netdev_max_backlog=300000
    #sudo sysctl net.core.somaxconn=20480
    #sudo sysctl net.ipv4.tcp_max_tw_buckets=2000000
    #sudo sysctl net.ipv4.tcp_timestamps=0
    #sudo sysctl vm.min_free_kbytes=65536
    #sudo sysctl net.ipv4.ip_forward=1
    #sudo sysctl net.ipv4.tcp_syncookies=1
    #sudo sysctl net.ipv4.tcp_synack_retries=2
    #sudo sysctl net.ipv4.conf.default.forwarding=1
    #sudo sysctl net.ipv4.conf.default.proxy_arp=1
    #sudo sysctl net.ipv4.conf.all.rp_filter=1
    #sudo sysctl net.ipv4.conf.default.send_redirects=1
    #sudo sysctl net.ipv4.conf.all.send_redirects=0

fi

echo -e "\n========================================================"
# Display OS version, Tor version & torrc in log
echo -e "Debian Version: \c" && cat /etc/debian_version
tor --version
obfs4proxy -version
cat /etc/tor/torrc
echo -e "========================================================\n"

# else default to run whatever the user wanted like "bash"
exec "$@"
